apiVersion: v1
kind: ConfigMap
metadata:
  name: synergychat-web-configmap
data:
  # Same port as API, but diferent pods dont share same ports.
  WEB_PORT: "8080"
  API_URL: http://synchatapi.internal
